//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_DaGreenciCode : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.daGreenciCode_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Trackpad
        {
            get
            {
                return SteamVR_Actions.daGreenciCode_Trackpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.daGreenciCode_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.daGreenciCode_Grip;
            }
        }
        
        public virtual SteamVR_Action_Pose ControllerPosition
        {
            get
            {
                return SteamVR_Actions.daGreenciCode_ControllerPosition;
            }
        }
        
        public virtual SteamVR_Action_Vibration Vibration
        {
            get
            {
                return SteamVR_Actions.daGreenciCode_Vibration;
            }
        }
    }
}
