//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_DaGreenciCode p_DaGreenciCode;
        
        public static SteamVR_Input_ActionSet_DaGreenciCode DaGreenciCode
        {
            get
            {
                return SteamVR_Actions.p_DaGreenciCode.GetCopy<SteamVR_Input_ActionSet_DaGreenciCode>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_DaGreenciCode = ((SteamVR_Input_ActionSet_DaGreenciCode)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_DaGreenciCode>("/actions/DaGreenciCode")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.DaGreenciCode};
        }
    }
}
