//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_daGreenciCode_Trigger;
        
        private static SteamVR_Action_Boolean p_daGreenciCode_Trackpad;
        
        private static SteamVR_Action_Boolean p_daGreenciCode_Menu;
        
        private static SteamVR_Action_Boolean p_daGreenciCode_Grip;
        
        private static SteamVR_Action_Pose p_daGreenciCode_ControllerPosition;
        
        private static SteamVR_Action_Vibration p_daGreenciCode_Vibration;
        
        public static SteamVR_Action_Boolean daGreenciCode_Trigger
        {
            get
            {
                return SteamVR_Actions.p_daGreenciCode_Trigger.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean daGreenciCode_Trackpad
        {
            get
            {
                return SteamVR_Actions.p_daGreenciCode_Trackpad.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean daGreenciCode_Menu
        {
            get
            {
                return SteamVR_Actions.p_daGreenciCode_Menu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean daGreenciCode_Grip
        {
            get
            {
                return SteamVR_Actions.p_daGreenciCode_Grip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose daGreenciCode_ControllerPosition
        {
            get
            {
                return SteamVR_Actions.p_daGreenciCode_ControllerPosition.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vibration daGreenciCode_Vibration
        {
            get
            {
                return SteamVR_Actions.p_daGreenciCode_Vibration.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.daGreenciCode_Trigger,
                    SteamVR_Actions.daGreenciCode_Trackpad,
                    SteamVR_Actions.daGreenciCode_Menu,
                    SteamVR_Actions.daGreenciCode_Grip,
                    SteamVR_Actions.daGreenciCode_ControllerPosition,
                    SteamVR_Actions.daGreenciCode_Vibration};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.daGreenciCode_Trigger,
                    SteamVR_Actions.daGreenciCode_Trackpad,
                    SteamVR_Actions.daGreenciCode_Menu,
                    SteamVR_Actions.daGreenciCode_Grip,
                    SteamVR_Actions.daGreenciCode_ControllerPosition};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.daGreenciCode_Vibration};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.daGreenciCode_Vibration};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.daGreenciCode_ControllerPosition};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.daGreenciCode_Trigger,
                    SteamVR_Actions.daGreenciCode_Trackpad,
                    SteamVR_Actions.daGreenciCode_Menu,
                    SteamVR_Actions.daGreenciCode_Grip};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.daGreenciCode_Trigger,
                    SteamVR_Actions.daGreenciCode_Trackpad,
                    SteamVR_Actions.daGreenciCode_Menu,
                    SteamVR_Actions.daGreenciCode_Grip};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_daGreenciCode_Trigger = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DaGreenciCode/in/Trigger")));
            SteamVR_Actions.p_daGreenciCode_Trackpad = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DaGreenciCode/in/Trackpad")));
            SteamVR_Actions.p_daGreenciCode_Menu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DaGreenciCode/in/Menu")));
            SteamVR_Actions.p_daGreenciCode_Grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DaGreenciCode/in/Grip")));
            SteamVR_Actions.p_daGreenciCode_ControllerPosition = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/DaGreenciCode/in/ControllerPosition")));
            SteamVR_Actions.p_daGreenciCode_Vibration = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/DaGreenciCode/out/Vibration")));
        }
    }
}
